### ISSUE TITLE
请问有没有我在校园，健康打卡的Docker版本

### ISSUE THREAD

**Issue by Norach-I** [ccqstark/WoZaiXiaoYuanPuncher-Docker#1]
下载了，在阿里云上配置，折腾了半天发现，对应的url不是健康打卡的。。。。。。而是日检日报的。字典的key对应不上。请问有没有健康打卡版的Docker版本。

**Comment by ccqstark** [comment]
你看我友链里其他人好像有做，我不维护啦因为压根就没人管你打没打卡😅

**Comment by ccqstark** [comment]
你好，我已经新增了健康打卡功能
