### ISSUE TITLE
日午检打不成功

### ISSUE THREAD

**Issue by 1837620622** [ccqstark/WoZaiXiaoYuanPuncher-Docker#2]
没办法求教

**Comment by ccqstark** [comment]
晨检还是晚检，晚检好像现在改最早打卡时间了，可能要改下源码

**Comment by 1837620622** [comment]
加个联系方式我折腾好几天啦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 上午8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ccqstark/WoZaiXiaoYuanPuncher-Docker] 日午检打不成功 (Issue #2)





 
晨检还是晚检，晚检好像现在改最早打卡时间了，可能要改下源码
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccqstark** [comment]
qq：1367305698

**Comment by 1837620622** [comment]
微信吧 我搜不到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ccqstark/WoZaiXiaoYuanPuncher-Docker] 日午检打不成功 (Issue #2)





 
qq：1367305698
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1837620622** [comment]
我加你vx啦 同意一下哥哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccqstark/WoZaiXiaoYuanPuncher-Docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 上午8:48
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [ccqstark/WoZaiXiaoYuanPuncher-Docker] 日午检打不成功 (Issue #2)





 
qq：1367305698
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccqstark** [comment]
没看到申请呀，qq号没错，vx号就在q号前面加个Q

**Comment by 1837620622** [comment]
搜不到 隐藏了吧 我vx加你了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccqstark/WoZaiXiaoYuanPuncher-Docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 上午8:54
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [ccqstark/WoZaiXiaoYuanPuncher-Docker] 日午检打不成功 (Issue #2)





 
没看到申请呀，qq号没错，vx号就在q号前面加个Q
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccqstark** [comment]
微信没看到申请呀，要不你发你vx我加你😂

**Comment by 1837620622** [comment]
1837620622




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 上午8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ccqstark/WoZaiXiaoYuanPuncher-Docker] 日午检打不成功 (Issue #2)





 
微信没看到申请呀，要不你发你vx我加你😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
